### ISSUE TITLE
0.5.0 roadmap

### ISSUE THREAD

**Issue by williamhorning** [williamhorning/bolt#18]
this isn't final but I need to keep track of this:

- [ ] handle guilded 502 and 503 errors better
- [ ] handle slash commands
- [ ] figure out data/embeds issue (guilded)
- [ ] figure out a way to deal with discord max character limit
- [ ] fix revolt permission errors
- [ ] don't just spit out terrible embed on errors, make the message useful to people
- [ ] Typescript rewrite
