### ISSUE TITLE
1.0.0 roadmap ish

### ISSUE THREAD

**Issue by williamhorning** [williamhorning/bolt#59]
- [ ] #19
- [ ] #39
- [ ] #36 
- [ ] fix guilded webhooks, again
- [ ] fix guilded duplication, again
- [ ] fix docker release
- [ ] move plugins outside of repo
  - [ ] make them depend on the JSR version of bolt 0.6 (still in this repo)
  - [ ] make them work as JSR packages (pass `--dry-run`)
  - [ ] publish to JSR
  - [ ] move to different repo
- [ ] move all repos to one org
- [ ] make plugins more independent of core since they could be really useful for others
